CREATE TABLE [dbo].[GiftCard] (
    [GIF_ID]               INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [GIF_NR]               VARCHAR (35) NOT NULL,
    [GIF_DESCRIPTION]      VARCHAR (30) NULL,
    [GIF_TOTALBALANCE]     FLOAT (53)   NULL,
    [GIF_OVERDRAFTLIMIT]   FLOAT (53)   NULL,
    [GIF_RESERVEDAMOUNT]   FLOAT (53)   NULL,
    [GIF_AVAILABLEBALANCE] FLOAT (53)   NULL,
    [GIF_CURRENTAMOUNT]    FLOAT (53)   NULL,
    [GIF_OVERDUEAMOUNT]    FLOAT (53)   NULL,
    [GIF_ISACTIVE]         CHAR (1)     NULL,
    [GIF_ISSUSPENDED]      CHAR (1)     NULL,
    [IsDeleted]            BIT          NOT NULL
);


GO

ALTER TABLE [dbo].[GiftCard]
    ADD CONSTRAINT [DF__GiftCard__GIF_AV__2116E6DF] DEFAULT ((0)) FOR [GIF_AVAILABLEBALANCE];


GO



ALTER TABLE [dbo].[GiftCard]
    ADD CONSTRAINT [DF__GiftCard__GIF_CU__220B0B18] DEFAULT ((0)) FOR [GIF_CURRENTAMOUNT];


GO



ALTER TABLE [dbo].[GiftCard]
    ADD CONSTRAINT [DF__GiftCard__GIF_IS__23F3538A] DEFAULT ('1') FOR [GIF_ISACTIVE];


GO



ALTER TABLE [dbo].[GiftCard]
    ADD CONSTRAINT [DF__GiftCard__GIF_IS__24E777C3] DEFAULT ('0') FOR [GIF_ISSUSPENDED];


GO



ALTER TABLE [dbo].[GiftCard]
    ADD CONSTRAINT [DF__GiftCard__GIF_OV__1F2E9E6D] DEFAULT ((0)) FOR [GIF_OVERDRAFTLIMIT];


GO



ALTER TABLE [dbo].[GiftCard]
    ADD CONSTRAINT [DF__GiftCard__GIF_OV__22FF2F51] DEFAULT ((0)) FOR [GIF_OVERDUEAMOUNT];


GO



ALTER TABLE [dbo].[GiftCard]
    ADD CONSTRAINT [DF__GiftCard__GIF_RE__2022C2A6] DEFAULT ((0)) FOR [GIF_RESERVEDAMOUNT];


GO



ALTER TABLE [dbo].[GiftCard]
    ADD CONSTRAINT [DF__GiftCard__GIF_TO__1E3A7A34] DEFAULT ((0)) FOR [GIF_TOTALBALANCE];


GO



ALTER TABLE [dbo].[GiftCard]
    ADD CONSTRAINT [DF_GiftCard_IsDeleted] DEFAULT ((0)) FOR [IsDeleted];


GO



ALTER TABLE [dbo].[GiftCard]
    ADD CONSTRAINT [GiftCard_PK] PRIMARY KEY CLUSTERED ([GIF_ID] ASC) WITH (FILLFACTOR = 90);


GO



