CREATE TABLE [dbo].[GIFTRANSACTIONS] (
    [GIT_ID]             INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [GIT_GIF_ID]         INT          NOT NULL,
    [GIT_REFNR]          VARCHAR (30) NULL,
    [GIT_DESCRIPTION]    VARCHAR (60) NULL,
    [GIT_DATETIME]       ROWVERSION   NOT NULL,
    [GIT_TYPE]           CHAR (1)     NOT NULL,
    [GIT_AMOUNT]         MONEY        NULL,
    [GIT_OPENINGBALANCE] MONEY        NULL,
    [GIT_CLOSINGBALANCE] MONEY        NULL,
    [IsDeleted]          BIT          NOT NULL
);


GO

ALTER TABLE [dbo].[GIFTRANSACTIONS]
    ADD CONSTRAINT [DF__GIFTRANSA__GIT_A__59C55456] DEFAULT ((0)) FOR [GIT_AMOUNT];


GO



ALTER TABLE [dbo].[GIFTRANSACTIONS]
    ADD CONSTRAINT [DF__GIFTRANSA__GIT_C__5BAD9CC8] DEFAULT ((0)) FOR [GIT_CLOSINGBALANCE];


GO



ALTER TABLE [dbo].[GIFTRANSACTIONS]
    ADD CONSTRAINT [DF__GIFTRANSA__GIT_O__5AB9788F] DEFAULT ((0)) FOR [GIT_OPENINGBALANCE];


GO



ALTER TABLE [dbo].[GIFTRANSACTIONS]
    ADD CONSTRAINT [DF_GIFTRANSACTIONS_IsDeleted] DEFAULT ((0)) FOR [IsDeleted];


GO



ALTER TABLE [dbo].[GIFTRANSACTIONS]
    ADD CONSTRAINT [GIFTRANSACTIONS_PK] PRIMARY KEY CLUSTERED ([GIT_ID] ASC) WITH (FILLFACTOR = 90);


GO



